project1: cell.cpp main.cpp residential.cpp
	g++ main.cpp cell.cpp region.cpp config.cpp residential.cpp industrial.cpp growth.cpp commercial.cpp garbageGrowth.cpp worker.cpp garbageCollection.cpp -o project1.exe
